# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-09 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='server',
            name='order',
        ),
        migrations.AddField(
            model_name='server',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='server',
            name='mobile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
